# Generated by Django 5.0.7 on 2024-07-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemoftheday',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='problemoftheday',
            name='problem_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='problemoftheday',
            unique_together={('date', 'problem_id')},
        ),
    ]
