# Generated by Django 5.0.7 on 2024-07-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('problem_id', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField()),
            ],
        ),
    ]
